image: continuumio/miniconda3:latest


pipelines:
  default:
    - step:
        name: Install requirements.
        caches:
          - conda
          - pip
        script: # Modify the commands below to build your repository.
          - conda env update --file env_cpttool.yml
    - parallel:
        - step: # Run tests
            name: Run tests and codecoverage.
            caches:
                - conda
                - pip
            script:
                - conda activate ours_environment
                - pytest -v --cov=CPTtool --cov-report html:test-reports/coverage unit_testing/
                - apt-get update && apt-get --yes install zip
                - zip -r test-reports/coverage.zip test-reports/coverage
                - pipe: atlassian/bitbucket-upload-file:0.3.1
                  variables:
                      BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                      BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                      FILENAME: "test-reports/coverage.zip"
        - step: # Create documentation
            name: Create documentation.
            caches:
                - conda
                - pip
            script:
                - conda activate ours_environment

definitions:
   caches:
     conda: ~/.conda/envs/rose
     codatarballs: /opt/conda/pkgs