import setuptools

# define setuptools
setuptools.setup(name="CPTtool",
                 version="1.1",
                 author="Deltares",
                 author_email="",
                 description="CPT processing tool",
                 long_description="Package for the processing of CPT and subsoil schematisation of OURS",
                 long_description_content_type="text/markdown",
                 url="",
                 packages=["CPTtool"],
                 package_dir={"CPTtool": "./CPTtool"},
                 package_data={"mypkg": ["./CPTtool/shapefiles/*"]},
                 python_requires=">=3.7",
                 options={"bdist_wheel": {"python_tag": "py3.7"}},
                 install_requires=["lxml>=4.3",
                                   "matplotlib>=3.1",
                                   "netcdf4>=1.4",
                                   "numpy>=1.16",
                                   "pandas>=0.24",
                                   "pyproj>=2.2",
                                   "pyshp>=2.1",
                                   "requests>=2.22",
                                   "rtree>=0.9.4",
                                   "scipy>=1.2.1",
                                   "setuptools>=41.0.1",
                                   "shapely>=1.6.4",
                                   "tqdm>=4.32.1"],
                 extras_require={"doc": ["sphinx>=2.1", "sphinxcontrib-bibtex>=0.4"],
                                 "test": ["coverage>=4.5", "teamcity-messages==1.25"],
                                 },
                 classifiers=["Programming Language :: Python :: 3.7",
                              "License :: OSI Approved :: EUPL-1.2",
                              "Operating System :: Microsoft :: Windows :: Windows 10",
                              ],
                 )
